import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/globals.css";

const nuninto = Nunito({
  weight: ["200", "300", "400", "500", "600", "700", "800", "1000"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nuninto.className} antialiased`}>{children}</body>
    </html>
  );
}
